### ISSUE TITLE
Getting ImportError: No module named cuda.load_textures

### ISSUE THREAD

**Issue by akashdexati** [svip-lab/impersonator#20]
Hi @StevenLiuWen @piaozhx @ak9250 
I followed the exact steps mentioned in README.md
On running <demo_swap.py> it runs into "ImportError: No module named cuda.load_textures"

```
akash@my-open-source-machine:~/impersonator$ python demo_swap.py 
Traceback (most recent call last):
  File "demo_swap.py", line 5, in <module>
    from models.swapper import Swapper
  File "/home/ubuntu/impersonator/models/swapper.py", line 7, in <module>
    from utils.nmr import SMPLRenderer
  File "/home/ubuntu/impersonator/utils/nmr.py", line 6, in <module>
    import neural_renderer as nr
  File "build/bdist.linux-x86_64/egg/neural_renderer/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/neural_renderer/load_obj.py", line 9, in <module>
ImportError: No module named cuda.load_textures
```

I have referred https://github.com/daniilidis-group/neural_renderer/issues/17
But in my case there is only one neural_renderer.

Can you please guide me on the issue.
Thanks

**Comment by TheCompAce** [comment]
akashdexati,

I have spent all day trying to get this to work. I created a new Environment with Python 3.6, and got everything setup (I also needed the Nvidia CUDA toolkit)

But now I am stuck with this error. (I tried the latest github of "neural_renderer" but that didn't compile like this one did.)

Any help with this would be great, I am on Windows 7.

**Comment by yeetan** [comment]
goto the directory of neural_renderer\neural_renderer, then run the python
>>> import neural_renderer.cuda.load_textures as load_textures_cuda
it works,
but when I got to the root directory of neural_renderer, it displays the error again,

**Comment by DavisDDD** [comment]
I had the same problem, I'm using pycharm. The problem is beacause the import package can't be in the same path with the demo.py. My solution is copy the /neural_renderer to another path, then add it as an external lib.
