### ISSUE TITLE
There are some bugs ，how to modify the code？thanks！

### ISSUE THREAD

**Issue by 853643520** [svip-lab/impersonator#24]
C:\Users\1152>python D:\Pytorch\impersonator-master\demo_imitator.py --gpu_ids 1
Traceback (most recent call last):
  File "D:\Pytorch\impersonator-master\demo_imitator.py", line 6, in <module>
    from models.imitator import Imitator
  File "D:\Pytorch\impersonator-master\models\imitator.py", line 8, in <module>
    from utils.nmr import SMPLRenderer
  File "D:\Pytorch\impersonator-master\utils\nmr.py", line 6, in <module>
    import neural_renderer as nr
ModuleNotFoundError: No module named 'neural_renderer'

**Comment by StevenLiuWen** [comment]
@853643520 
It need to install `neural_renderer` at first (as illustrated in READEME.md)
```bash
cd thirdparty/neural_renderer
python setup.py install
```
If you  enncounter some problems with Windows platform when installing `neural_renderer`, please refer https://github.com/svip-lab/impersonator/issues/2

**Comment by 853643520** [comment]
OK，thanks a lot！
