### ISSUE TITLE
argparse.ArgumentError: argument --load_path: conflicting option string: --load_path

### ISSUE THREAD

**Issue by SihYingChen** [svip-lab/impersonator#37]
Hi! Thanks for your awesome job!
When I ran the demo_imitation.py, I had this problem. 
I try to comment out 'load_path' in test_options.py or base_options.py, but it didn't work.
Could you help me to figure it out? Thank you!

> Traceback (most recent call last):
  File "demo_view.py", line 157, in <module>
    opt = TestOptions().parse()
  File "/workspace/Impersonator/options/base_options.py", line 75, in parse
    self.initialize()
  File "/workspace/Impersonator/options/test_options.py", line 16, in initialize
    help='pretrained model path')
  File "/opt/conda/lib/python3.6/argparse.py", line 1352, in add_argument
    return self._add_action(action)
  File "/opt/conda/lib/python3.6/argparse.py", line 1715, in _add_action
    self._optionals._add_action(action)
  File "/opt/conda/lib/python3.6/argparse.py", line 1556, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/opt/conda/lib/python3.6/argparse.py", line 1366, in _add_action
    self._check_conflict(action)
  File "/opt/conda/lib/python3.6/argparse.py", line 1505, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/conda/lib/python3.6/argparse.py", line 1514, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --load_path: conflicting option string: --load_path

**Comment by StevenLiuWen** [comment]
@SihYingChen It's a bug in last version, clone the latest codes.
