### ISSUE TITLE
ImportError: load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z16THPVariable_WrapN5torch8autograd8VariableE

### ISSUE THREAD

**Issue by studabyd** [svip-lab/impersonator#40]
when i run demo_imitator.py the error is that and my python version is 3.6.4, Thank you for your help

Traceback (most recent call last):
  File "demo_imitator.py", line 6, in <module>
    from models.imitator import Imitator
  File "/home/lcy/impersonator-master/models/imitator.py", line 8, in <module>
    from utils.nmr import SMPLRenderer
  File "/home/lcy/impersonator-master/utils/nmr.py", line 6, in <module>
    import neural_renderer as nr
  File "/home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/load_obj.py", line 9, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z16THPVariable_WrapN5torch8autograd8VariableE
(python36) lcy@lcy:~/impersonator-master$ python demo_imitator.py --gpu_ids 1 
Traceback (most recent call last):
  File "demo_imitator.py", line 6, in <module>
    from models.imitator import Imitator
  File "/home/lcy/impersonator-master/models/imitator.py", line 8, in <module>
    from utils.nmr import SMPLRenderer
  File "/home/lcy/impersonator-master/utils/nmr.py", line 6, in <module>
    import neural_renderer as nr
  File "/home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/load_obj.py", line 9, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/lcy/anaconda3/envs/python36/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z16THPVariable_WrapN5torch8autograd8VariableE

**Comment by piaozhx** [comment]
refer #35
