### ISSUE TITLE
CUDA version error and generate nothing

### ISSUE THREAD

**Issue by gosser123** [svip-lab/impersonator#43]
I used 'python demo_imitator.py --gpu_ids 0 --batch_size 1 ' to run the demo , but it warned " Error in forward_face_index_map_1: CUDA driver version is insufficient for CUDA runtime version, Error in forward_face_index_map_2: CUDA driver version is insufficient for CUDA runtime version" , finally it runed successfuly,  "Completed! All demo videos are save in ./outputs/results/demos/imitators" , but There were only a few folders under the folder without the demo videos.   
    my torch version is 1.0.0, CUDA version is 10.0,  Is it the wrong version, could you help me ?

**Comment by gosser123** [comment]
when I used "python demo_swap.py --gpu_ids 0 --batch_size 1", it reported errors, 
`load face model from assets/pretrains/sphere20a_20171020.pth
step: 49; total: 3.061088; cyc: 0.145273; str: 0.061302; fid: 0.992965; msk: 0.000475: 100%|█████████████████████████████████████████████████████████| 50/50 [00:33<00:00,  1.40it/s]

                        Personalization: completed...

                        Swapping: ./assets/src_imgs/imper_A_Pose/009_5_1_000.jpg wear the clothe of ./assets/src_imgs/fashion_woman/fashionWOMENBlouses_Shirtsid0000666802_4full.jpg...
Traceback (most recent call last):
  File "demo_swap.py", line 62, in <module>
    visualizer=visualizer)
  File "/home/lgy/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/lgy/PycharmProjects/impersonator/models/swapper.py", line 213, in swap
    src_part_mask = (torch.sum(src_info['part'][:, selected_ids, ...], dim=1) != 0).bool()
AttributeError: 'Tensor' object has no attribute 'bool'
`
