### ISSUE TITLE
AttributeError: module 'neural_renderer' has no attribute 'rasterize_face_index_map_and_weight_map'

### ISSUE THREAD

**Issue by kashyappiyush1998** [svip-lab/impersonator#71]
On running demo_swap.py I get error - 

    `    

------------ Options -------------
T_pose: False
batch_size: 4
bg_ks: 13
bg_model: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth
bg_replace: False
body_seg: False
cam_strategy: smooth
checkpoints_dir: ./outputs/checkpoints/
cond_nc: 3
data_dir: /p300/datasets/iPER
dataset_mode: iPER
debug: False
do_saturate_mask: False
face_model: assets/pretrains/sphere20a_20171020.pth
front_warp: False
ft_ks: 3
gen_name: impersonator
gpu_ids: 0
has_detector: False
hmr_model: assets/pretrains/hmr_tf2pt.pth
image_size: 256
images_folder: images_HD
ip:
is_train: False
load_epoch: 0
load_path: ./outputs/checkpoints/lwb_imper_fashion_place/net_epoch_30_id_G.pth
map_name: uv_seg
model: impersonator
n_threads_test: 0
name: running
norm_type: instance
only_vis: False
output_dir: ./outputs/results/
part_info: assets/pretrains/smpl_part_info.json
port: 31100
post_tune: False
pri_path: ./assets/samples/A_priors/imgs
repeat_num: 6
save_res: False
serial_batches: False
smpl_model: assets/pretrains/smpl_model.pkl
smpls_folder: smpls
src_path:
swap_part: body
test_ids_file: val.txt
tex_size: 3
tgt_path:
time_step: 10
train_ids_file: train.txt
uv_mapping: assets/pretrains/mapper.txt
view_params: R=0,90,0/t=0,0,0
-------------- End ----------------
./outputs/checkpoints/running
Network impersonator was created
1.6.0+cu101
Loading net: ./outputs/checkpoints/lwb_imper_fashion_place/net_epoch_30_id_G.pth
Network deepfillv2 was created
1.6.0+cu101
Loading net: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth
Traceback (most recent call last):
  File "demo_swap.py", line 51, in <module>
    swapper.swap_setup(src_path, tgt_path)
  File "C:\Users\kashy\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "D:\data\impersonator\models\swapper.py", line 195, in swap_setup
    self.src_info = self.personalize(src_path, src_smpl)
  File "C:\Users\kashy\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "D:\data\impersonator\models\swapper.py", line 116, in personalize
    src_f2verts, src_fim, src_wim = self.render.render_fim_wim(src_info['cam'], src_info['verts'])
  File "D:\data\impersonator\utils\nmr.py", line 277, in render_fim_wim
    fim, wim = nr.rasterize_face_index_map_and_weight_map(faces, self.image_size, False)
AttributeError: module 'neural_renderer' has no attribute 'rasterize_face_index_map_and_weight_map'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

    `

**Comment by koalaaaaaaaaa** [comment]
same problem，bro, do you have any ideas now?

**Comment by kashyappiyush1998** [comment]
Gave up long time ago

**Comment by FinallyKiKi** [comment]
The same question from (https://github.com/svip-lab/impersonator/issues/60)
