### ISSUE TITLE
where can i download the simples.zip,the link is failure "https://pan.baidu.com/s/1xAI96709Gvqahq9uYAEXYA"

### ISSUE THREAD

**Issue by zetaodu** [svip-lab/impersonator#85]

**Comment by zetaodu** [comment]
I run the command:
python run_imitator.py --gpu_ids 0 --model imitator --output_dir ./outputs/results/      --src_path      ./assets/samples/src_imgs/men1_256.jpg        --tgt_path      ./assets/samples/ref_imgs/024_8_2        --has_detector  --post_tune   --front_warp  --save_res --ip http://10.10.10.100 --port 31102 

but get the error:
`Traceback (most recent call last):
  File "run_imitator.py", line 227, in <module>
    adaptive_personalize(test_opt, imitator, visualizer)
  File "run_imitator.py", line 205, in adaptive_personalize
    imitator.personalize(opt.src_path, visualizer=None)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/impersonator/models/imitator.py", line 85, in personalize
    ori_img = cv_utils.read_cv2_img(src_path)
  File "/impersonator/utils/cv_utils.py", line 18, in read_cv2_img
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'`
